### PR TITLE
Changed HTTP Status Codes and Methods with constants defined in http lib

### PR DESCRIPTION
**Pull request by meelunae**
## Description
As I am approaching the codebase to take care of the golint related issues that are currently open, I took care of some linter errors that came out through a dry run of golangci-lint.
 
## Changes
Replaced string literals for HTTP methods and integers for status codes as required from the linter errors.

## Requirements
No requirements should be needed as this just replaces some parts of the code with an equivalent that is compliant with what I have read in the majority of the codebase.

### CODE REVIEW

**Comment by KyleJu** [comment]
@meelunae Thanks for the PR! The changes look good and I will approve it after the CI passes!

**Comment by meelunae** [comment]
Hi @KyleJu! Thank you for looking into the PR! I have noticed the CI is failing because I forgot a !=, I'll proceed to fix it right now! My bad as my environment is kinda messy since the environment isn't working on macOS! :(

**Comment by meelunae** [comment]
Should be good! Please feel free to relaunch CI whenever and sorry again about the mistake :)

**Comment by meelunae** [comment]
Hello @KyleJu, I've noticed that the CI tests passed! Is this safe to merge?
Thanks!

**Review by KyleJu — APPROVED** [review]

**Comment by KyleJu** [comment]
> Hello @KyleJu, I've noticed that the CI tests passed! Is this safe to merge? Thanks!

Thanks!

**Pull request merged**
