### PR TITLE
Change interop colors

### PR DESCRIPTION
**Pull request by lukebjerring**
## Description

Part of https://github.com/web-platform-tests/wpt.fyi/issues/150

Uses (equivalent rgb values of) the `--paper-{grey, red, deep-orange, orange, light-green}-500` material colors.

## Review

https://interop-colors-dot-wptdashboard.appspot.com/interop

### CODE REVIEW

**Comment by zcorpan** [comment]
Did you intend to match the first or second mockup, or try something else?

**Comment by zcorpan** [comment]
The first mockup has red in the middle  (2/4).

The second mockup has red on the left (0/4), going towards green (4/4).

It seemed like @foolip liked the second approach better.

**Comment by foolip** [comment]
I do like the red&rarr;green better than red in the middle. However, I think maybe 0/4 should be reddest of them all and not gray.

**Comment by lukebjerring** [comment]
lol - didn't notice! Disclaimer: I struggle with https://colormax.org/color-blind-test/, which is why I defer to the material palette and avoid color decisions where possible!

**Comment by lukebjerring** [comment]
@foolip - well... have to say, 0/4 is _technically_ interoperable... hence grey made sense to me.

Happy to change to super-duper red if we are all in agreement there.

**Comment by zcorpan** [comment]
red->green is OK with me :)

**Comment by lukebjerring** [comment]
Re-deployed with red, deep-orange, orange, yellow, green.. thoughts?

**Comment by zcorpan** [comment]
Is it the same green as is used in results/? https://interop-colors-dot-wptdashboard.appspot.com/results/2dcontext the green seems brighter here I think.

Otherwise LGTM

**Pull request merged**
