### PR TITLE
Use ?complete=true as default query for /api/runs

### PR DESCRIPTION
**Pull request by foolip**
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/441.

### CODE REVIEW

**Comment by foolip** [comment]
The fix works at least: https://api-runs-complete-dot-wptdashboard-staging.appspot.com/results/

**Comment by mdittmer** [comment]
@foolip and @Hexcles what do you think about the commits I've added? I think we should answer "when do we _not_ want to insist on complete runs?" and encode that logic where the query parameters are computed.

One thing that I haven't included, but we should consider, is whether or not we should add `complete=true` when `sha=latest` (in addition to when `sha` is not specified).

**Comment by foolip** [comment]
This is a much better approach, thanks Mark! Some things that need tuning IMHO.

https://api-runs-complete-dot-wptdashboard-staging.appspot.com/results/?complete=false still shows complete results, i.e. I don't think there's any way to show a mix of runs now.

https://api-runs-complete-dot-wptdashboard-staging.appspot.com/results/?label=stable looks great, that's what I think should be on our front page now.

https://api-runs-complete-dot-wptdashboard-staging.appspot.com/results/?label=experimental also looks good, although I don't understand why. Does /api/runs have a limit on how far back it will look?

If ?complete=false makes that view look like https://wpt.fyi/results/?label=experimental does now (including an Edge run) then I think this will be all good!

**Comment by foolip** [comment]
Filed https://github.com/web-platform-tests/wpt.fyi/issues/468 about the behavior I'm not sure about.

**Comment by Hexcles** [comment]
Hmm, looks like we need to add `complete` as a property of `TestRunsBase`, similar to other params like `sha`. And pass the value of `complete` from Go to the web components.

**Pull request merged**
