### PR TITLE
Support live reloading of the local dev server

### LINKED ISSUE #2310: [Docker] Docker is not watching file changes in the local build
After Go 1.12 migration, docker is not watching file changes in the local development. Before Go 1.12, after starting `./util/docker-dev/web_server.sh`, any changes will reflect in the wpt.fyi local build right away.

I am suspecting https://github.com/web-platform-tests/wpt.fyi/pull/2267, where `docker build -t wptd-dev .` is changed to `docker pull webplatformtests/wpt.fyi:latest`

### PR DESCRIPTION
**Pull request by Hexcles**
There are two kinds of loading/packaging that happens at startup/build
time that prevents the server from serving live, local files.

1. node_modules, dynamic components & templates are packaged into the
   binary using packr (as part of `go generate`).
2. All templates are parsed *once* at startup. Furthermore, changes in
   Go source code require rebuilding the server.

Thus, we employ two workarounds to achieve live reloading:
1. Disable packr when serving locally (via a new `go_build_dev` target).
2. Use inotify to watch template and Go source changes; rebuild and
   restart the server when changes happen.

This should provide a good local dev experience (perhaps even better
than dev_appserver due to faster reload time).

Drive-by: suppress some code comments from the output of make.

Fixes #2310

### CODE REVIEW

**Comment by KyleJu** [comment]
I couldn't get local build to work with this change, as the server returns `Failed to load resource: the server responded with a status of 404 (Not Found)`. The build steps for `./util/docker-dev/web_server.sh` are also substantially shorter than before. Below is the local log:

`
$ ./util/docker-dev/web_server.sh
if [[ "$(which inotifywait)" == "" ]]; then \
	sudo apt-get install -qqy --no-install-suggests inotify-tools; \
fi
[  2020-12-16 01:22:18  INFO  ]  Building web server...
if [[ "$(which git)" == "" ]]; then sudo apt-get install -qqy --no-install-suggests git; fi
go build -tags skippackr ./webapp/web
[  2020-12-16 01:22:20  INFO  ]  Starting web server. Port forwarded to host: 8080
2020/12/16 06:22:22 Serving on :8080...
time="2020-12-16T06:22:29Z" level=info msg="307 GET /"
time="2020-12-16T06:22:29Z" level=info msg="200 GET /results/"
time="2020-12-16T06:22:29Z" level=info msg="404 GET /node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js"
time="2020-12-16T06:22:29Z" level=info msg="404 GET /node_modules/@polymer/app-route/app-location.js"
time="2020-12-16T06:22:29Z" level=info msg="404 GET /node_modules/@polymer/app-route/app-route.js"
time="2020-12-16T06:22:29Z" level=info msg="404 GET /node_modules/@polymer/iron-pages/iron-pages.js"
time="2020-12-16T06:22:29Z" level=info msg="404 GET /node_modules/@polymer/paper-dialog/paper-dialog.js"
time="2020-12-16T06:22:29Z" level=info msg="404 GET /node_modules/@polymer/iron-icon/iron-icon.js"
time="2020-12-16T06:22:29Z" level=info msg="404 GET /node_modules/@polymer/iron-icons/iron-icons.js"
time="2020-12-16T06:22:29Z" level=info msg="404 GET /node_modules/@polymer/paper-menu-button/paper-menu-button.js"
time="2020-12-16T06:22:29Z" level=info msg="404 GET /node_modules/@polymer/paper-icon-button/paper-icon-button.js"
time="2020-12-16T06:22:29Z" level=info msg="404 GET /node_modules/@polymer/paper-button/paper-button.js"
time="2020-12-16T06:22:29Z" level=info msg="404 GET /node_modules/@polymer/paper-checkbox/paper-checkbox.js"
time="2020-12-16T06:22:29Z" level=info msg="404 GET /node_modules/@polymer/paper-toggle-button/paper-toggle-button.js"
time="2020-12-16T06:22:29Z" level=info msg="404 GET /node_modules/@polymer/paper-item/paper-item.js"
time="2020-12-16T06:22:29Z" level=info msg="404 GET /node_modules/@polymer/paper-input/paper-input.js"
time="2020-12-16T06:22:29Z" level=info msg="404 GET /node_modules/@vaadin/vaadin-date-picker/vaadin-date-picker-light.js"
time="2020-12-16T06:22:29Z" level=info msg="404 GET /node_modules/@vaadin/vaadin-date-picker/vaadin-date-picker.js"
time="2020-12-16T06:22:29Z" level=info msg="404 GET /node_modules/@polymer/paper-tooltip/paper-tooltip.js"
time="2020-12-16T06:22:29Z" level=info msg="404 GET /node_modules/@polymer/paper-tabs/paper-tab.js"
time="2020-12-16T06:22:29Z" level=info msg="404 GET /node_modules/@polymer/paper-tabs/paper-tabs.js"
time="2020-12-16T06:22:29Z" level=info msg="404 GET /node_modules/@polymer/paper-toast/paper-toast.js"
time="2020-12-16T06:22:30Z" level=info msg="200 GET /dynamic-components/wpt-env-flags.js"
`

**Comment by Hexcles** [comment]
Looks like `node_modules` is missing, which should be fixed in the latest commit. Please try again.

**Comment by KyleJu** [comment]
> Looks like `node_modules` is missing, which should be fixed in the latest commit. Please try again.

I still have difficulties in the build, and it gives me the same errors. Does it work on your machine?

**Comment by Hexcles** [comment]
@KyleJu yeah it does work for me. Can you paste the full logs?

**Comment by KyleJu** [comment]
Error logs:

GET http://0.0.0.0:8080/node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js net::ERR_ABORTED 404 (Not Found)
wpt-app.js:9 GET http://0.0.0.0:8080/node_modules/@polymer/app-route/app-location.js net::ERR_ABORTED 404 (Not Found)
wpt-app.js:10 GET http://0.0.0.0:8080/node_modules/@polymer/app-route/app-route.js net::ERR_ABORTED 404 (Not Found)
wpt-app.js:11 GET http://0.0.0.0:8080/node_modules/@polymer/iron-pages/iron-pages.js net::ERR_ABORTED 404 (Not Found)
github-login.js:7 GET http://0.0.0.0:8080/node_modules/@polymer/paper-dialog/paper-dialog.js net::ERR_ABORTED 404 (Not Found)
github-login.js:11 GET http://0.0.0.0:8080/node_modules/@polymer/iron-icon/iron-icon.js net::ERR_ABORTED 404 (Not Found)
github-login.js:12 GET http://0.0.0.0:8080/node_modules/@polymer/iron-icons/iron-icons.js net::ERR_ABORTED 404 (Not Found)
github-login.js:13 GET http://0.0.0.0:8080/node_modules/@polymer/paper-button/paper-button.js net::ERR_ABORTED 404 (Not Found)
github-login.js:14 GET http://0.0.0.0:8080/node_modules/@polymer/paper-icon-button/paper-icon-button.js net::ERR_ABORTED 404 (Not Found)
github-login.js:15 GET http://0.0.0.0:8080/node_modules/@polymer/paper-menu-button/paper-menu-button.js net::ERR_ABORTED 404 (Not Found)
github-login.js:17 GET http://0.0.0.0:8080/node_modules/@polymer/paper-toggle-button/paper-toggle-button.js net::ERR_ABORTED 404 (Not Found)
wpt-flags.js:11 GET http://0.0.0.0:8080/node_modules/@polymer/paper-item/paper-item.js net::ERR_ABORTED 404 (Not Found)
wpt-flags.js:10 GET http://0.0.0.0:8080/node_modules/@polymer/paper-checkbox/paper-checkbox.js net::ERR_ABORTED 404 (Not Found)
test-runs-query-builder.js:10 GET http://0.0.0.0:8080/node_modules/@polymer/paper-input/paper-input.js net::ERR_ABORTED 404 (Not Found)
wpt-permalinks.js:12 GET http://0.0.0.0:8080/node_modules/@polymer/paper-tabs/paper-tabs.js net::ERR_ABORTED 404 (Not Found)
test-runs-query-builder.js:17 GET http://0.0.0.0:8080/node_modules/@vaadin/vaadin-date-picker/vaadin-date-picker.js net::ERR_ABORTED 404 (Not Found)
test-runs-query-builder.js:16 GET http://0.0.0.0:8080/node_modules/@vaadin/vaadin-date-picker/vaadin-date-picker-light.js net::ERR_ABORTED 404 (Not Found)
wpt-permalinks.js:13 GET http://0.0.0.0:8080/node_modules/@polymer/paper-toast/paper-toast.js net::ERR_ABORTED 404 (Not Found)
wpt-permalinks.js:11 GET http://0.0.0.0:8080/node_modules/@polymer/paper-tabs/paper-tab.js net::ERR_ABORTED 404 (Not Found)
test-search.js:7 GET http://0.0.0.0:8080/node_modules/@polymer/paper-tooltip/paper-tooltip.js net::ERR_ABORTED 404 (Not Found)

**Comment by KyleJu** [comment]
[console_log.txt](https://github.com/web-platform-tests/wpt.fyi/files/5711349/console_log.txt)

**Comment by KyleJu** [comment]
Tested in the local build and works with changes on both server side and frontend side. The only caveat is that `disable cache` in the network panel should be checked and the devtools needs to be open when live reload

**Review by KyleJu — APPROVED** [review]

**Comment by stephenmcgruer** [comment]
> Tested in the local build and works with changes on both server side and frontend side. The only caveat is that disable cache in the network panel should be checked and the devtools needs to be open when live reload

Should this be documented somewhere? Was it previously true or is this a new requirement?

**Comment by Hexcles** [comment]
That's the general behaviour of Devtools and it's not new. The "disable cache" checkbox doesn't stick if you close Devtools.

Alternatively, you can use Ctrl/Command-R to force reload.

**Pull request merged**
