### PR TITLE
Add maximum color difference and total different pixel count to reftest analyzer

### PR DESCRIPTION
**Pull request by dbaron**
This is really halfway between a feature request and a PR.  I've written code for it -- but I haven't tested that code since setting up a development environment looked like a decent amount of work.  So there's some chance this code might work, but it likely requires some modifications to get it running correctly.

## Description

This adds the number of different pixels and the maximum color component difference to the reftest analyzer.  This information is useful for adding `<meta name=fuzzy>` annotations as described in https://web-platform-tests.org/writing-tests/reftests.html#fuzzy-matching

## Review Information

Unknown.  I haven't actually tested it.  Like I said, this is halfway between a feature request and a PR.  I'd like to be able to use this feature on the "COMPARE" links on pages like https://wpt.fyi/results/css/css-transforms/css-skew-002.html?label=experimental&label=master .

### CODE REVIEW

**Comment by KyleJu** [comment]
@foolip the code itself looks good. Could you take a second look

**Comment by hatho286** [comment]
> This is really halfway between a feature request and a PR.  I've written code for it -- but I haven't tested that code since setting up a development environment looked like a decent amount of work.  So there's some chance this code might work, but it likely requires some modifications to get it running correctly.
> 
> 
> ## Description
> 
> This adds the number of different pixels and the maximum color component difference to the reftest analyzer.  This information is useful for adding `<meta name=fuzzy>` annotations as described in https://web-platform-tests.org/writing-tests/reftests.html#fuzzy-matching
> 
> ## Review Information
> 
> Unknown.  I haven't actually tested it.  Like I said, this is halfway between a feature request and a PR.  I'd like to be able to use this feature on the "COMPARE" links on pages like https://wpt.fyi/results/css/css-transforms/css-skew-002.html?label=experimental&label=master .

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
@KyleJu have you tested this in a staging environment?

**Comment by foolip** [comment]
Staging deployment was fixed in https://github.com/web-platform-tests/wpt.fyi/issues/2643, let me try to close and reopen to retrigger CI...

**Comment by KyleJu** [comment]
@foolip The staging deployment is [here](https://maxdiff-dot-wptdashboard-staging.uk.r.appspot.com/results/?label=experimental&label=master&aligned)

**Pull request merged**
