### PR TITLE
Show master/merge icons on /runs page

### PR DESCRIPTION
**Pull request by lukebjerring**
## Description
Gives a visual cue for `pr_head` and `master` labels, now that we'll occasionally have both in the same view.

### CODE REVIEW

**Comment by foolip** [comment]
https://master-icons-dot-wptdashboard-staging.appspot.com/runs?label=azure doesn't show the master icon for the runs that aren't PRs, is that a bug?

**Comment by lukebjerring** [comment]
@Hexcles - got an icon in mind for `pr_base` ?

**Comment by lukebjerring** [comment]
Not really; runs don't have a concept of PR number.
What's extra strange that the commits should both be the same (the SHA of the commit that caused the run) - is it possible that Azure is misconfigured and not overriding the revision with the commit that started the check ( for `pr_base`, specifically )?

**Comment by lukebjerring** [comment]
Wait; nevermind. Both `pr_head` and `pr_base` are in the group; let me fix the code.

**Comment by foolip** [comment]
Yeah, I didn't do anything to override the commit. Seems like it'd be best to record all 3 commits involved for both merge and base runs, so that we can tell if the comparison is valid?

**Comment by lukebjerring** [comment]
Maybe, but that's tangential to this PR.

**Pull request merged**
