### PR TITLE
[TEST] Change the Trusted Origin

### PR DESCRIPTION
**Pull request by KyleJu**
Test /api/metadata/triage from a trusted origin. See #1728 for more info.

Test it from https://kyleju.github.io/

e.g. input: {"/css/css-align/gaps/gap-animation-001.html":[{"url":"foo", "product":"chrome", "results": [{"status": 6 }]}]}

### CODE REVIEW

**Comment by KyleJu** [comment]
Login is enabled in staging.wpt.fyi instead and the testing from trusted third parties is complete. Close this PR

**Comment by stephenmcgruer** [comment]
I want to try this out, so re-opening briefly. :D

**Comment by stephenmcgruer** [comment]
Ah, I think the oauth bot changed and things can't be tested so easily. Oh well.

**Comment by Hexcles** [comment]
> Ah, I think the oauth bot changed and things can't be tested so easily. Oh well.

Could you elaborate?

**Comment by stephenmcgruer** [comment]
I tried to sign in to staging.wpt.fyi, was successful logging in but still got 401s when sending the request. Used the deployment of this PR instead but wasn't able to sign in (got token error issues). I didn't really investigate, just assumed it was because things have been changed.

**Comment by Hexcles** [comment]
This can be tested in a staging deployment because it's on a different domain (appspot.com) and neither cookies or GitHub OAuth callback works.

**Pull request closed without merging**
