### PR TITLE
Make harness status "OK" grey rather than green

### PR DESCRIPTION
**Pull request by stephenmcgruer**
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/1553

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
@Hexcles I do *not* want to merge this without figuring out the testing situation (I'd really like to land a test to make sure we don't regress this again), but feel free to take a look and tell me if this naive change is a bad way to fix the bug :D

**Comment by Hexcles** [comment]
This LGTM / i.e. this is the right fix.

For testing, you can add an assertion for the color class here:
https://github.com/web-platform-tests/wpt.fyi/blob/5aa9db4a190a096f930be25f71002bb035d58bbb/webapp/components/test/test-file-results.html#L46-L54

**Comment by foolip** [comment]
Is there a staging deployment for this?

**Comment by stephenmcgruer** [comment]
> Is there a staging deployment for this?

Unlikely, as I don't know how to do that! Poked around for documentation and didn't find any; do you know how it's normally done?

**Comment by foolip** [comment]
It's supposed to happen automatically but it must be broken now.

**Comment by stephenmcgruer** [comment]
Ok, this is ready for real review now, thanks :). I've added some tests + updated the README with some stuff that was helpful to me.

**Comment by Hexcles** [comment]
I don't know why the tests aren't running. @stephenmcgruer could you merge master? I think your branch base point might be before the recent changes to GitHub Actions.

**Comment by stephenmcgruer** [comment]
I screwed up the merge so ended up rebasing and force-pushing. Lmk if its still not working.

**Comment by Hexcles** [comment]
> I screwed up the merge so ended up rebasing and force-pushing. Lmk if its still not working.

Oops, yeah it's all because I changed your PR directly :( Sorry

**Comment by foolip** [comment]
I have a `pushf` alias for `push --force-with-lease` to avoid accidentally overwriting changes I hadn't fetched. Should be the default mode :)

**Comment by Hexcles** [comment]
Ah I see! GitHub Actions are not running because I set the triggering condition to `push` without `pull_request`, so PRs coming from a fork won't trigger them.

Let me fix the config.

**Comment by stephenmcgruer** [comment]
Close/open to kick the bots now that @Hexcles fixed the config

**Comment by stephenmcgruer** [comment]
Not clear why https://github.com/web-platform-tests/wpt.fyi/pull/1554/checks?check_run_id=271590687 failed - some sort of timeout? @Hexcles ?

**Comment by Hexcles** [comment]
That's really weird. The Firefox test in question started at [13:04:28 GMT](https://github.com/web-platform-tests/wpt.fyi/pull/1554/checks?check_run_id=271590687#step:3:639) and we got the timeout error at [13:04:44 GMT](https://github.com/web-platform-tests/wpt.fyi/pull/1554/checks?check_run_id=271590687#step:3:708), which is merely half a minute.

I suspect something is wrong with web component tester, which is not actively maintained.

I'm going to retry the checks.

**Comment by Hexcles** [comment]
Re-opened #1352 to track the timeout in web component tests. I'm going to admin-merge this PR.

**Pull request merged**
