### PR TITLE
move interop data outside of static (fixes #3132)

### LINKED ISSUE #3132: Interop 2023: "Math Functions" could be labelled as "CSS Math Functions"?
At first, I thought that was about some methods in the ECMAScript `Math` object. People may understand that's CSS, but it could be better if being more precise. What do you think?

### PR DESCRIPTION
**Pull request by racheljay**
## Description
This PR moves the data that was previously in `components/static/interop-data.json` to a `.js` file outside of the static directory as outlined in the discussion for #3142.

## Changes
`components/static/interop-data.json` was previously removed and this PR adds that data to `components/interop-data.js`. It is now imported directly into `interop.js` and accessed by `fetchYearData()`.

### CODE REVIEW

**Comment by racheljay** [comment]
I don't have permission to request reviewers but this is ready for review @DanielRyanSmith @KyleJu. I'm also getting a failing check that looks to be caused by a permissions issue/missing client secret file.

**Comment by KyleJu** [comment]
> I don't have permission to request reviewers but this is ready for review @DanielRyanSmith @KyleJu. I'm also getting a failing check that looks to be caused by a permissions issue/missing client secret file.

Would you mind trying uploading this PR from a branch, rather than a fork? I think there are credential protections for PRs from a fork

**Comment by racheljay** [comment]
> > I don't have permission to request reviewers but this is ready for review @DanielRyanSmith @KyleJu. I'm also getting a failing check that looks to be caused by a permissions issue/missing client secret file.
> 
> @racheljay Would you mind trying uploading this PR from a branch, rather than a fork? I think there are credential protections for PRs from a fork.

I tried doing a direct push but I am getting this error: 
```ERROR: Permission to web-platform-tests/wpt.fyi.git denied to racheljay.```
The repo settings might need to be updated to allow me to push.

**Comment by KyleJu** [comment]
> > > I don't have permission to request reviewers but this is ready for review @DanielRyanSmith @KyleJu. I'm also getting a failing check that looks to be caused by a permissions issue/missing client secret file.
> > 
> > 
> > @racheljay Would you mind trying uploading this PR from a branch, rather than a fork? I think there are credential protections for PRs from a fork.
> 
> I tried doing a direct push but I am getting this error: `ERROR: Permission to web-platform-tests/wpt.fyi.git denied to racheljay.` The repo settings might need to be updated to allow me to push.

I just added you as a collaborator to this project. You should be able to push after accepting the invite! Let me know if you have any other questions

**Comment by racheljay** [comment]
Thanks @KyleJu! It looks like I can't convert this PR so I'll close it and make a new one.

**Pull request closed without merging**
