### PR TITLE
Add a minimal configuration file for Azure Pipelines

### PR DESCRIPTION
**Pull request by foolip**
@lukebjerring as suggested, here's a skeleton of how we could use Azure Pipelines to bunch of steps to run every week.

### CODE REVIEW

**Comment by foolip** [comment]
In order to actually register the pipeline in Azure DevOps I had to let it create a PR: https://github.com/web-platform-tests/wpt.fyi/pull/1117

(There's a way around that, but it's elaborate and I forgot.)

**Comment by Hexcles** [comment]
I'm out of loop: any reason we'd like to do the release on Azure instead of Travis?

**Comment by foolip** [comment]
Because it's possible to schedule builds at specific times. With Travis it's the time you set it up the first time.

**Comment by foolip** [comment]
One can of course make sure to be around at the right time once and then it's fine, but @lukebjerring liked this idea. I guess it'll duplicate some setup of gcloud SDK, etc.?

**Comment by Hexcles** [comment]
Oh, that's sad... Hopefully our Dockerized setup would just work without a hitch on Azure.

**Pull request closed without merging**
