### PR TITLE
Support chrome ios wptrunner result in FYI

### PR DESCRIPTION
**Pull request by sj0602**
Add the Chrome iOS product since the work to upload test runs is done.

### CODE REVIEW

**Review by past — COMMENTED** [review]
This is a clean revert of #3569, but it still suffers from the broken icon. Can you fix this?

**Comment by WeizhongX** [comment]
481e1b9e71e3c40168b3e2b2750a71a2aa915a40 is a similar one that add icon for webview.

**Review by WeizhongX — APPROVED** [review]

**Comment by sj0602** [comment]
> This is a clean revert of #3569, but it still suffers from the broken icon. Can you fix this?

Oh yes, I will create another PR to fix that issue now.
Thanks.

**Comment by sj0602** [comment]
https://github.com/web-platform-tests/wpt.fyi/pull/3755 this should fix the logo issue.
We already have the ios platform logo, just make sure chrome_ios use the same chrome logo as chrome_android.

**Comment by past** [comment]
Can you add the icon change as a commit in this PR? This way the change is self-contained, which helps with maintenability and reverts. I will merge this afterwards.

**Comment by sj0602** [comment]
> Can you add the icon change as a commit in this PR? This way the change is self-contained, which helps with maintenability and reverts. I will merge this afterwards.

Done, updated.
Could you help me to merge this?
Many thanks.

**Comment by past** [comment]
Oh, heh, it looks like you did this as I was typing my comment. Thanks!

**Review by past — APPROVED** [review]

**Comment by sj0602** [comment]
> Oh, heh, it looks like you did this as I was typing my comment. Thanks!

Yep, thank you!

**Pull request merged**
