### PR TITLE
Add diff to query builder

### PR DESCRIPTION
**Pull request by lukebjerring**
## Description
Adds a tickbox for showing a diff to the builder.

This required an unfortunate amount of refactoring :(

## Review Information
Select 2 products in the query builder, tick 'diff', submit.

### CODE REVIEW

**Comment by foolip** [comment]
I tried this on https://diff-dot-wptdashboard-staging.appspot.com but it doesn't seem to work. The checkbox doesn't add `&diff` to the URL, and when I manually add it, the checkbox also doesn't seem to remove `&diff` from the URL.

**Comment by foolip** [comment]
Alright, now it works.

As a very minor nit for some other PR, I ended up at https://diff-dot-wptdashboard-staging.appspot.com/results/?aligned&product=chrome%5Bstable%5D&product=chrome%5Bbeta%5D&diff and it would more aesthetically pleasing to have `&aligned&diff` at the end, rather than split across like this.

**Comment by lukebjerring** [comment]
Your comment sounds like approval but you did not approve the PR - any other concerns?

**Comment by foolip** [comment]
Oh, sorry, I just tested to see that it worked and commented, but haven't actually looked at the code at all yet, closed the tab and forgot.

**Pull request merged**
