### PR TITLE
Fix up result history chart UX

### PR DESCRIPTION
**Pull request by mdittmer**
- Fixed height
- When hidden, issue waning with 'Show anyway' button
- Reset 'Show anyway' state when tests, chunkSize, labels, or isFeasible changes

### CODE REVIEW

**Comment by Hexcles** [comment]
Thoughts after playing with the UI:

1. This is much better than before! Less jank, less magic (regarding when a graph would show up), more control. Awesome!
2. The graph is smaller than before. And the legend is now completely hidden in ellipses...
3. Can we fix the y-axis always to [0, 1]? Scale graphs that don't start from 0 are misleading; and what's worse is graphs that *sometimes* start from 0 but sometimes not. (I know this is not a new issue introduced by this PR.)

**Comment by lukebjerring** [comment]
This is going to clash with #376

**Comment by lukebjerring** [comment]
@Hexcles - re 3) above: we snuck that in, in #376

**Comment by mdittmer** [comment]
@lukebjerring and @Hexcles is this basically unnecessary now that #376 merged?

**Comment by lukebjerring** [comment]
The 'not feasible' case should probably still be displayed in the UI (currently the graph just doesn't load).

**Pull request closed without merging**
