### PR TITLE
Add permissive CORS for /api/search

### PR DESCRIPTION
**Pull request by lukebjerring**
## Description
Mozilla would like to use it externally.

### CODE REVIEW

**Comment by jgraham** [comment]
I tried updating my app to point at the staging server here, and I"m still getting a 400 for the options request; you should be able to see the failure at https://jgraham.github.io/wptdash/

**Comment by lukebjerring** [comment]
> Request Method: OPTIONS

Looks like we don't implement the OPTIONS http methods (just POST and GET). I'll open a separate issue for that.

If we did, it'd return.. the information I am giving you manually, I guess.

**Comment by jgraham** [comment]
The `OPTIONS` request has to return the right `Access-Control-*` headers so that the browser knows it's permitted to make the real `POST` request, c.f. https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request

**Comment by jgraham** [comment]
Seems like the most straightforward option here is just to add a route matching all options requests when configuring the router somewhere like https://github.com/web-platform-tests/wpt.fyi/blob/e604b98f451b6c7c01f2ccfb2a2d7dde029c34a2/shared/routing.go#L19

```
router.Methods("OPTIONS").handlerFunc(
  func(w http.ResponseWriter, r *http.Request) {
     w.Header().Add("Access-Control-Allow-Origin", "*")
     w.Header().Add("Access-Control-Allow-Methods", "POST,GET,OPTIONS")
     // whatever's needed here to actually send the response
  })
```

Or since you are already using mux, there's existing gorilla middleware to handle this: https://github.com/gorilla/handlers/blob/master/cors.go

**Comment by lukebjerring** [comment]
Driveby fixes https://github.com/web-platform-tests/wpt.fyi/issues/1106 too

**Comment by lukebjerring** [comment]
OK, allowing content-type seemed to stop the 403. I don't actually do anything with it yet.

Note that your query shows much less results than [this equivalent](https://cors-dot-wptdashboard-staging.appspot.com/results/?sha=e1d9e660a5b1eb9ee26193f2c71d26673f764e19&label=master&label=experimental&product=chrome&product=firefox&product=safari&q=%28firefox%3A%21pass+%26+firefox%3A%21ok%29+%28chrome%3Aok%7Cchrome%3Apass%29+%28safari%3Aok%7Csafari%3Apass%29) - I think the search should be `(firefox:!pass & firefox:!ok) (chrome:ok|chrome:pass) (safari:ok|safari:pass)`

(which expands as 

    {"query":{"exists":[{"and":[{"product":"firefox","status":{"not":"PASS"}},{"product":"firefox","status":{"not":"OK"}}]},{"or":[{"product":"chrome","status":"OK"},{"product":"chrome","status":"PASS"}]},{"or":[{"product":"safari","status":"OK"},{"product":"safari","status":"PASS"}]}]}

**Pull request merged**
