### PR TITLE
Update chrome ios wptrunner logo

### PR DESCRIPTION
**Pull request by sj0602**
Use the same way as chrome_android does.

### CODE REVIEW

**Comment by sj0602** [comment]
@past Could you help me to take a look?
Many thanks.

**Comment by sj0602** [comment]
@WeizhongX

**Comment by KyleJu** [comment]
LGTM, but this PR should be a part of #3754

**Comment by sj0602** [comment]
> LGTM, but this PR should be a part of #3754

Updated this change to #3754

**Pull request closed without merging**
