### PR TITLE
Put product builder in collapsible

### PR DESCRIPTION
**Pull request by lukebjerring**
## Description
Puts the builder in a collapsible that closes when you submit.

## Review Information
- Visit /flags, enable `queryBuilder`
- Visit /esults, click the pencil, submit a query
- See it collapse

### CODE REVIEW

**Comment by foolip** [comment]
Expanding and collapsing work (neat!) but after I'm done, I end up at https://builder-collapse-dot-wptdashboard-staging.appspot.com/results/?label=stable&product=chrome&aligned with no results loaded. Loading that in a new tab directly is also broken. Ought to be a regression in this PR because staging.wpt.fyi works.

**Comment by lukebjerring** [comment]
That'll be the regression from https://github.com/web-platform-tests/wpt.fyi/pull/629

**Comment by foolip** [comment]
Should the fix go in before this PR? I'll review the code here in any case.

**Comment by foolip** [comment]
Approved, by wait, can this be tested?

**Comment by lukebjerring** [comment]
No, I don't think it can be tested easily.

**Pull request merged**
