### PR TITLE
[WIP]Triage endpoint

### PR DESCRIPTION
**Pull request by KyleJu**
This PR introduces /api/metadata PATCH endpoint to automatically create PR and check in wpt failures/flakiness to wpt-metadata repositories. 

This CL should be landed after TODOs are complete and Github oauth flow is created. 
TODO: Improving logging

Testing Instructions: 
curl --header "Content-Type: application/json" -d '{\"/a/b.html\":[{\"url\":\"foo\", \"product\":\"chrome\"}]}'  --request PATCH https://triage-endpoint-dot-wptdashboard-staging.appspot.com/api/metadata?

Result:
https://github.com/web-platform-tests/wpt-metadata/pull/44/files

Debug Info:
https://pantheon.corp.google.com/logs/viewer?project=wptdashboard-staging&resource=gae_app%2Fmodule_id%2Fdefault%2Fversion_id%2Ftriage-endpoint&minLogLevel=0&expandAll=false&timestamp=2019-11-12T20:54:33.321000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2019-11-12T19:04:56.066Z&interval=PT1H&logName=projects%2Fwptdashboard-staging%2Flogs%2Fstderr&logName=projects%2Fwptdashboard-staging%2Flogs%2Fappengine.googleapis.com%252Frequest_log&scrollTimestamp=2019-11-12T20:53:23.587861000Z&dateRangeUnbound=forwardInTime

### CODE REVIEW

**Comment by KyleJu** [comment]
@stephenmcgruer Ready for a preliminary review, besides the TODO items

**Comment by Hexcles** [comment]
Note: this PR is mostly missing access control.

**Comment by KyleJu** [comment]
Note: Access control done. Leave auto merge as TODO for security reason. 

TODO:
Split refactoring on login.go to a separate CL
Refactor the code/gomock to get ready for testing.

**Comment by KyleJu** [comment]
Closing this PR because it is a duplicate from #1728

**Pull request closed without merging**
