### PR TITLE
Reduce size of interop dashboard circles

### LINKED ISSUE #3126: Reduce size of the 2023 Interop score circles
They look quite large, especially in a 2 column layout like the one used for 2023.

font-size: 4em;  instead of 5em seems to give a decent size IMO.

### PR DESCRIPTION
**Pull request by nt1m**
Fixes #3126

## Description
TODO

## Review Information
TODO

## Changes
TODO

## Requirements
TODO

### CODE REVIEW

**Comment by jcscottiii** [comment]
test link from CI job: https://reduce-circle-size-dot-wptdashboard-staging.uk.r.appspot.com/interop-2023

**Review by jcscottiii — COMMENTED** [review]
These changes look fine to me. But I will let @DanielRyanSmith give the final LGTM because Daniel worked closely with the team on the design on the page.

**Review by DanielRyanSmith — APPROVED** [review]
LGTM, thanks for the changes 🙂

**Comment by nt1m** [comment]
@DanielRyanSmith do you know what's going on with the web_components_test check?

**Comment by DanielRyanSmith** [comment]
It looks like we have a test regression after [a recent dependency update](https://github.com/web-platform-tests/wpt.fyi/commit/5d208930270008e49e42b9faceeb46d98a3e4d51) that will need to be fixed.

**Pull request merged**
