### PR TITLE
Update api/search GET/POST methods in doc

### PR DESCRIPTION
**Pull request by KyleJu**
Update api/search GET/POST methods in doc

### CODE REVIEW

**Comment by Hexcles** [comment]
Oh thank you! I finally realized what I missed a few days ago. Let me revert some recent doc changes first.

**Comment by foolip** [comment]
Oh wow, so the GET variant is the useful one that I didn't know existed. Why doesn't the wpt.fyi front end use this, given that the actual runs are also returned?

**Comment by Hexcles** [comment]
@foolip it does **not** support structured queries. `q` simply filters by *test names*.

**Comment by foolip** [comment]
Oh, yeah that's not what I want at all :)

**Review by Hexcles — APPROVED** [review]

**Comment by KyleJu** [comment]
@Hexcles Thanks Robert!

**Pull request merged**
