### PR TITLE
[searchcache] Triaged Search Atom

### PR DESCRIPTION
**Pull request by KyleJu**
Fix for #1760

Todo: support wildcards

### CODE REVIEW

**Comment by KyleJu** [comment]
@Hexcles do you know why the deployed searchcache is 404?

**Comment by Hexcles** [comment]
The searchcache does not have a homepage so it's 404.

**Comment by KyleJu** [comment]
Notes to myself: Also need to support wildcards

**Comment by KyleJu** [comment]
branch name too long. closing this PR

**Pull request closed without merging**
