### PR TITLE
Use GitHub Personal Access token for wpt-pr-bot

### LINKED ISSUE #272: Move auto-deploy credentials to bot account
Currently, the GITHUB_TOKEN (in the Travis secret) used for commenting after a deployment is from the `lukebjerring` user. (as of https://github.com/web-platform-tests/wpt.fyi/pull/41)

This should be changed to be the bot account.

### PR DESCRIPTION
**Pull request by zcorpan**
Fixes #272.

---

The access token was created for the wpt-pr-bot account, ticking the "repo" checkbox (which includes  repo:status, repo_deployment, public_repo, repo:invite). I hope this is sufficient scope.

Using travis-cli, I ran
```
travis encrypt GITHUB_TOKEN=blah
```
and pasted the encrypted token in 2 places in .travis.yml.

### CODE REVIEW

**Comment by zcorpan** [comment]
From #272

> log into travis CLI as the bot account

I didn't do this. Do I need to re-do it?

**Comment by lukebjerring** [comment]
Thanks!

**Comment by lukebjerring** [comment]
Hi @zcorpan - in https://github.com/web-platform-tests/wpt.fyi/pull/1442 I've added the need for the token to include permissions for repo_deployment. Given that you say you included that permission, I'm [seeing an unexpected 404](https://travis-ci.com/web-platform-tests/wpt.fyi/jobs/229475474#L894) in the logs. I'm not sure if GH have changed things under the hood or something, any ideas?

**Comment by lukebjerring** [comment]
Second thought here is that maybe the wpr-pr-bot doesn't have deploy rights on the repo, so a token invoking those rights can't exercise them in any case?

**Comment by zcorpan** [comment]
The bot has a personal access token called "wpt.fyi" with these permissions

>  repo  Full control of private repositories
  repo:status  Access commit status
  repo_deployment  Access deployment status
  public_repo  Access public repositories
  repo:invite  Access repository invitations

I'm not familiar enough with how the deployment works to say what's wrong, but it looks like the token has sufficient permissions at least.

**Comment by jugglinmike** [comment]
@lukebjerring If this were a problem with the token, I would expect a 401 or 403. That's admittedly a weak signal, though. Maybe try running `curl` locally with an all-access token and see where that leads.

**Comment by lukebjerring** [comment]
@jugglinmike - I would too, hence why I commented as such here; turns out they deliberately 404 to obfuscate the issue (in the case of private repos, you don't even want to reveal it exists, I guess).
https://developer.github.com/v3/troubleshooting/#why-am-i-getting-a-404-error-on-a-repository-that-exists

https://github.com/web-platform-tests/wpt.fyi/pull/274#issuecomment-526415453 was indeed the issue; added `wpt-pr-bot` to `wpt.fyi` and voila!

**Pull request merged**
