### PR TITLE
Update score for Accessibility Testing (70%)

### PR DESCRIPTION
**Pull request by zcorpan**
See https://github.com/web-platform-tests/interop-2023-accessibility-testing/issues/3#issuecomment-1546395755

### CODE REVIEW

**Comment by zcorpan** [comment]
https://github.com/web-platform-tests/wpt.fyi/actions/runs/5057204533/jobs/9075667648?pr=3332 failed, but not clear to me why

**Comment by KyleJu** [comment]
Looks like one of the interop tests failed:
```
chrome 113               ✖ components/test/interop-data.html » InteropData » should match interop-data.json exactly

  expected { Object (2021, 2022, ...) } to deeply equal { Object (2021, 2022, ...) }
    <unknown> at      assert.deepEqual at /components/chai/chai.js:2054:0
    <unknown> at   Context.<anonymous> at interop-data.html:16:0
```

**Comment by DanielRyanSmith** [comment]
We keep an identical copy of the data at `webapp/static/interop-data.json` per request, as this file is used by some of Mozilla's tools. If you make this change in that file as well, it should fix the test failure. I'll update the test message to be more verbose about the fix.

**Review by KyleJu — APPROVED** [review]

**Comment by zcorpan** [comment]
Fixed

**Pull request merged**
