### PR TITLE
Add "android_webview" as browser name

### PR DESCRIPTION
**Pull request by WeizhongX**
Add "android_webview" as browser name

### CODE REVIEW

**Comment by KyleJu** [comment]
I see a test failure:
```
chrome 96                ✖ components/test/test-search.html » <test-search> » Parser/interpreter » browser test status eq

  Line 1, col 15:
> 1 | chrome_android:ok
                    ^
Expected end of input: expected false to be true
    <unknown> at   Function.assert.isTrue at /components/chai/chai.js:2199:0
    <unknown> at         assertQueryParse at test-search.html:23:0
    <unknown> at      Context.<anonymous> at test-search.html:147:0
```

**Comment by WeizhongX** [comment]
> 

Thanks! Any suggestion on how to fix this? Is this because now we have "chrome" and "chrome_android", and they have common prefix?

@foolip

**Comment by KyleJu** [comment]
The staging deployment can be viewed here https://fix-product-dot-wptdashboard-staging.uk.r.appspot.com/results/?label=experimental&label=master&aligned

**Comment by WeizhongX** [comment]
> The staging deployment can be viewed here https://fix-product-dot-wptdashboard-staging.uk.r.appspot.com/results/?label=experimental&label=master&aligned

Yes I can see the webview result from link above. As all the check is passed now, can I get an approve for this one? We can leave change for chrome_android for a different PR.

**Review by KyleJu — APPROVED** [review]

**Pull request merged**
