### PR TITLE
Persist /interop/ sha param

### PR DESCRIPTION
**Pull request by lukebjerring**
## Description
Works on #214 

Changes in-page navigation behaviour to be shared between `/interop/` and `/results/` for consistency, using inheritance. This means that specifying a SHA will persist.

Note that the SHA itself does not yet affect the datastore query.

## Review
- See auto-deployed environment
- Navigate to /interop?sha=1234567890
- Filter into a folder, e.g. 2dcontext
- Observe ?sha is still on the path
- Hit the back button
- Observe ?sha is still on the path

### CODE REVIEW

**Comment by Hexcles** [comment]
This change looks good overall, but the integration test seems to be failing. @lukebjerring any idea why?

**Comment by Hexcles** [comment]
ping @lukebjerring in case you missed it

**Comment by Hexcles** [comment]
@lukebjerring why's the linter complaining about some go internal stuff?

```
# golang.org/x/tools/go/internal/gcimporter
../tools/go/internal/gcimporter/bimport.go:541:8: undefined: types.NewInterface2
../tools/go/internal/gcimporter/iimport.go:540:10: undefined: types.NewInterface2
```

**Comment by lukebjerring** [comment]
re: /x/tools error: See https://github.com/web-platform-tests/wpt.fyi/pull/268

**Pull request merged**
