### PR TITLE
Add links for investigation areas

### LINKED ISSUE #3140: Interop investigation projects don't have their links in the dashboard
Quoted from the description on https://wpt.fyi/interop-2023 (emphasis is mine):

> Investigation Projects are group projects chosen by the Interop team to be taken on this year. They involve doing the work of moving the web standards or web platform tests community forward regarding a particularly tricky issue. The percentage represents the amount of progress made towards project goals. **Project titles link to Git repos where work is happening.** Read the issues for details.

However, those project titles are not links:

image

I initially thought that maybe the new investigation projects have not yet created their git repos. But the links are also missing for previous investigation projects, which definitely have them:
image

### PR DESCRIPTION
**Pull request by stof**
## Description

This adds links on the investigation areas in the interop dashboard.
Closes #3140

### CODE REVIEW

**Review by DanielRyanSmith — APPROVED** [review]
Thanks for taking care of this!

**Comment by stof** [comment]
@DanielRyanSmith what is the next step to get this merged ?

**Comment by DanielRyanSmith** [comment]
Feel free to squash and merge your approved PRs and we'll deploy them in the next release. 🙂

**Comment by stof** [comment]
@DanielRyanSmith As an external contributor, I cannot merge my PRs. I don't have write access to this repository.

**Comment by DanielRyanSmith** [comment]
Ah! I did not realize that was the case. I'm not sure if that's intentional, but regardless, I'll go ahead and merge them for now. Thanks for letting us know!

**Pull request merged**
