### PR TITLE
Separate the first row in test-file-results display

### PR DESCRIPTION
**Pull request by lukebjerring**
## Description
More subtle fix for https://github.com/web-platform-tests/wpt.fyi/issues/449

### CODE REVIEW

**Comment by foolip** [comment]
Looking at https://rowsplit-dot-wptdashboard-staging.appspot.com/results/ambient-light/AmbientLightSensor-disabled-by-feature-policy.https.html?label=stable&aligned=true, I can't tell the difference. Am I looking at the wrong thing?

**Comment by lukebjerring** [comment]
Sorry, child PR didn't seem to work so well. Reset now that #594 is landed. PTAL.

**Comment by foolip** [comment]
Still can't see a difference, tried https://rowsplit-dot-wptdashboard-staging.appspot.com/results/dom/historical.html?label=stable&aligned=true this time. Do you have a URL that works for you?

**Comment by lukebjerring** [comment]
There's an extra 8px of whitespace under the headers.

**Comment by foolip** [comment]
Can you share a screenshot of what you see? Seems like we must be getting different content server or something?

**Comment by lukebjerring** [comment]
So.. it's not different because the change is already present somehow (bad merge?) My bad.

**Comment by lukebjerring** [comment]
.. I will tweak this here.

**Pull request merged**
